#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BalloonContextMenuFrame

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "TLClient_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_BalloonContextMenuFrame.BP_BalloonContextMenuFrame_C
// 0x0010 (0x1600 - 0x15F0)
class UBP_BalloonContextMenuFrame_C final : public UTLUserWidgetContextMenuList
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x15F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTLVerticalBox*                         MenuList;                                          // 0x15F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_BalloonContextMenuFrame(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BalloonContextMenuFrame_C">();
	}
	static class UBP_BalloonContextMenuFrame_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BalloonContextMenuFrame_C>();
	}
};
static_assert(alignof(UBP_BalloonContextMenuFrame_C) == 0x000010, "Wrong alignment on UBP_BalloonContextMenuFrame_C");
static_assert(sizeof(UBP_BalloonContextMenuFrame_C) == 0x001600, "Wrong size on UBP_BalloonContextMenuFrame_C");
static_assert(offsetof(UBP_BalloonContextMenuFrame_C, UberGraphFrame) == 0x0015F0, "Member 'UBP_BalloonContextMenuFrame_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_BalloonContextMenuFrame_C, MenuList) == 0x0015F8, "Member 'UBP_BalloonContextMenuFrame_C::MenuList' has a wrong offset!");

}

