#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DropDown_Frame

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_DropDown_Frame.BP_DropDown_Frame_C.ExecuteUbergraph_BP_DropDown_Frame
// 0x0004 (0x0004 - 0x0000)
struct BP_DropDown_Frame_C_ExecuteUbergraph_BP_DropDown_Frame final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_DropDown_Frame_C_ExecuteUbergraph_BP_DropDown_Frame) == 0x000004, "Wrong alignment on BP_DropDown_Frame_C_ExecuteUbergraph_BP_DropDown_Frame");
static_assert(sizeof(BP_DropDown_Frame_C_ExecuteUbergraph_BP_DropDown_Frame) == 0x000004, "Wrong size on BP_DropDown_Frame_C_ExecuteUbergraph_BP_DropDown_Frame");
static_assert(offsetof(BP_DropDown_Frame_C_ExecuteUbergraph_BP_DropDown_Frame, EntryPoint) == 0x000000, "Member 'BP_DropDown_Frame_C_ExecuteUbergraph_BP_DropDown_Frame::EntryPoint' has a wrong offset!");

}

