#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HeadUI_PcSimple_Optimization2C

#include "Basic.hpp"

#include "BP_HeadUI_PcSimple_Optimization2C_classes.hpp"
#include "BP_HeadUI_PcSimple_Optimization2C_parameters.hpp"


namespace SDK
{

// Function BP_HeadUI_PcSimple_Optimization2C.BP_HeadUI_PcSimple_Optimization2C_C.ExecuteUbergraph_BP_HeadUI_PcSimple_Optimization2C
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_HeadUI_PcSimple_Optimization2C_C::ExecuteUbergraph_BP_HeadUI_PcSimple_Optimization2C(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HeadUI_PcSimple_Optimization2C_C", "ExecuteUbergraph_BP_HeadUI_PcSimple_Optimization2C");

	Params::BP_HeadUI_PcSimple_Optimization2C_C_ExecuteUbergraph_BP_HeadUI_PcSimple_Optimization2C Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HeadUI_PcSimple_Optimization2C.BP_HeadUI_PcSimple_Optimization2C_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_HeadUI_PcSimple_Optimization2C_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HeadUI_PcSimple_Optimization2C_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HeadUI_PcSimple_Optimization2C.BP_HeadUI_PcSimple_Optimization2C_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_HeadUI_PcSimple_Optimization2C_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HeadUI_PcSimple_Optimization2C_C", "PreConstruct");

	Params::BP_HeadUI_PcSimple_Optimization2C_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

