#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HUD_EXP_Tooltip

#include "Basic.hpp"

#include "BP_HUD_EXP_Tooltip_classes.hpp"
#include "BP_HUD_EXP_Tooltip_parameters.hpp"


namespace SDK
{

// Function BP_HUD_EXP_Tooltip.BP_HUD_EXP_Tooltip_C.ExecuteUbergraph_BP_HUD_EXP_Tooltip
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_HUD_EXP_Tooltip_C::ExecuteUbergraph_BP_HUD_EXP_Tooltip(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HUD_EXP_Tooltip_C", "ExecuteUbergraph_BP_HUD_EXP_Tooltip");

	Params::BP_HUD_EXP_Tooltip_C_ExecuteUbergraph_BP_HUD_EXP_Tooltip Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HUD_EXP_Tooltip.BP_HUD_EXP_Tooltip_C.CustomEvent_0
// (BlueprintCallable, BlueprintEvent)

void UBP_HUD_EXP_Tooltip_C::CustomEvent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HUD_EXP_Tooltip_C", "CustomEvent_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HUD_EXP_Tooltip.BP_HUD_EXP_Tooltip_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_HUD_EXP_Tooltip_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HUD_EXP_Tooltip_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

