#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ItemTooltip_Equip_Frame

#include "Basic.hpp"

#include "BP_ItemTooltip_Equip_Frame_classes.hpp"
#include "BP_ItemTooltip_Equip_Frame_parameters.hpp"


namespace SDK
{

// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.ExecuteUbergraph_BP_ItemTooltip_Equip_Frame
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ItemTooltip_Equip_Frame_C::ExecuteUbergraph_BP_ItemTooltip_Equip_Frame(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "ExecuteUbergraph_BP_ItemTooltip_Equip_Frame");

	Params::BP_ItemTooltip_Equip_Frame_C_ExecuteUbergraph_BP_ItemTooltip_Equip_Frame Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnUpdateDropActionGuide
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bShow                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bIsConsole                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_ItemTooltip_Equip_Frame_C::OnUpdateDropActionGuide(const bool bShow, const bool bIsConsole)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnUpdateDropActionGuide");

	Params::BP_ItemTooltip_Equip_Frame_C_OnUpdateDropActionGuide Parms{};

	Parms.bShow = bShow;
	Parms.bIsConsole = bIsConsole;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnUpdateFocusMoveAreaGuide
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bShow                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_ItemTooltip_Equip_Frame_C::OnUpdateFocusMoveAreaGuide(const bool bShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnUpdateFocusMoveAreaGuide");

	Params::BP_ItemTooltip_Equip_Frame_C_OnUpdateFocusMoveAreaGuide Parms{};

	Parms.bShow = bShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnChangeScrollContentAutonFocus
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bFocus                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_ItemTooltip_Equip_Frame_C::OnChangeScrollContentAutonFocus(const bool bFocus)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnChangeScrollContentAutonFocus");

	Params::BP_ItemTooltip_Equip_Frame_C_OnChangeScrollContentAutonFocus Parms{};

	Parms.bFocus = bFocus;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnUpdateTotalMenu
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bInEnable                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bInShow                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_ItemTooltip_Equip_Frame_C::OnUpdateTotalMenu(bool bInEnable, bool bInShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnUpdateTotalMenu");

	Params::BP_ItemTooltip_Equip_Frame_C_OnUpdateTotalMenu Parms{};

	Parms.bInEnable = bInEnable;
	Parms.bInShow = bInShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnExistStats
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    InIsExist                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_ItemTooltip_Equip_Frame_C::OnExistStats(bool InIsExist)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnExistStats");

	Params::BP_ItemTooltip_Equip_Frame_C_OnExistStats Parms{};

	Parms.InIsExist = InIsExist;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnUpdateTradableIcon
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsTradable                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bIsOverwriteExchangeable                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_ItemTooltip_Equip_Frame_C::OnUpdateTradableIcon(bool bIsTradable, bool bIsOverwriteExchangeable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnUpdateTradableIcon");

	Params::BP_ItemTooltip_Equip_Frame_C_OnUpdateTradableIcon Parms{};

	Parms.bIsTradable = bIsTradable;
	Parms.bIsOverwriteExchangeable = bIsOverwriteExchangeable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnUpdateEnchant
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bInIsVisible                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bInIsEnable                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   InMaxLevel                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ItemTooltip_Equip_Frame_C::OnUpdateEnchant(bool bInIsVisible, bool bInIsEnable, int32 InMaxLevel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnUpdateEnchant");

	Params::BP_ItemTooltip_Equip_Frame_C_OnUpdateEnchant Parms{};

	Parms.bInIsVisible = bInIsVisible;
	Parms.bInIsEnable = bInIsEnable;
	Parms.InMaxLevel = InMaxLevel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnUpdateEnchantTransfer
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bInIsVisible                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bInIsEnable                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   InCount                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ItemTooltip_Equip_Frame_C::OnUpdateEnchantTransfer(bool bInIsVisible, bool bInIsEnable, int32 InCount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnUpdateEnchantTransfer");

	Params::BP_ItemTooltip_Equip_Frame_C_OnUpdateEnchantTransfer Parms{};

	Parms.bInIsVisible = bInIsVisible;
	Parms.bInIsEnable = bInIsEnable;
	Parms.InCount = InCount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnUpdateEquipPositionName
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             InName                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBP_ItemTooltip_Equip_Frame_C::OnUpdateEquipPositionName(const class FText& InName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnUpdateEquipPositionName");

	Params::BP_ItemTooltip_Equip_Frame_C_OnUpdateEquipPositionName Parms{};

	Parms.InName = std::move(InName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnCollectionClick
// (BlueprintCallable, BlueprintEvent)

void UBP_ItemTooltip_Equip_Frame_C::OnCollectionClick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnCollectionClick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_ItemTooltip_Equip_Frame_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "PreConstruct");

	Params::BP_ItemTooltip_Equip_Frame_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnUpdateCollectable
// (Event, Protected, BlueprintEvent)
// Parameters:
// ETLItemCollectableState                 InCollectableState                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InConditionLevel                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ItemTooltip_Equip_Frame_C::OnUpdateCollectable(ETLItemCollectableState InCollectableState, int32 InConditionLevel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnUpdateCollectable");

	Params::BP_ItemTooltip_Equip_Frame_C_OnUpdateCollectable Parms{};

	Parms.InCollectableState = InCollectableState;
	Parms.InConditionLevel = InConditionLevel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnUpdateStorable
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsStorable                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_ItemTooltip_Equip_Frame_C::OnUpdateStorable(bool bIsStorable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnUpdateStorable");

	Params::BP_ItemTooltip_Equip_Frame_C_OnUpdateStorable Parms{};

	Parms.bIsStorable = bIsStorable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnUpdateDestructible
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsDestructible                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_ItemTooltip_Equip_Frame_C::OnUpdateDestructible(bool bIsDestructible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnUpdateDestructible");

	Params::BP_ItemTooltip_Equip_Frame_C_OnUpdateDestructible Parms{};

	Parms.bIsDestructible = bIsDestructible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnUpdateDecomposable
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsDecomposable                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_ItemTooltip_Equip_Frame_C::OnUpdateDecomposable(bool bIsDecomposable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnUpdateDecomposable");

	Params::BP_ItemTooltip_Equip_Frame_C_OnUpdateDecomposable Parms{};

	Parms.bIsDecomposable = bIsDecomposable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnUpdateTradePriceInfo
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// bool                                    InShowTradePrice                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FText                             RecentPriceText                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class FText                             SaleCountText                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBP_ItemTooltip_Equip_Frame_C::OnUpdateTradePriceInfo(bool InShowTradePrice, const class FText& RecentPriceText, const class FText& SaleCountText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnUpdateTradePriceInfo");

	Params::BP_ItemTooltip_Equip_Frame_C_OnUpdateTradePriceInfo Parms{};

	Parms.InShowTradePrice = InShowTradePrice;
	Parms.RecentPriceText = std::move(RecentPriceText);
	Parms.SaleCountText = std::move(SaleCountText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnEmphasizeComponent
// (Event, Protected, BlueprintEvent)
// Parameters:
// EItemTooltipComponent                   InComponent                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    InEmphasize                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_ItemTooltip_Equip_Frame_C::OnEmphasizeComponent(EItemTooltipComponent InComponent, bool InEmphasize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnEmphasizeComponent");

	Params::BP_ItemTooltip_Equip_Frame_C_OnEmphasizeComponent Parms{};

	Parms.InComponent = InComponent;
	Parms.InEmphasize = InEmphasize;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnUpdateRequireLevel
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   InRequireLevel                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InPcLevel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ItemTooltip_Equip_Frame_C::OnUpdateRequireLevel(int32 InRequireLevel, int32 InPcLevel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnUpdateRequireLevel");

	Params::BP_ItemTooltip_Equip_Frame_C_OnUpdateRequireLevel Parms{};

	Parms.InRequireLevel = InRequireLevel;
	Parms.InPcLevel = InPcLevel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnPosetUpdateContent
// (Event, Protected, BlueprintEvent)

void UBP_ItemTooltip_Equip_Frame_C::OnPosetUpdateContent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnPosetUpdateContent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnUpdateCategoryName
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             InName                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBP_ItemTooltip_Equip_Frame_C::OnUpdateCategoryName(const class FText& InName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnUpdateCategoryName");

	Params::BP_ItemTooltip_Equip_Frame_C_OnUpdateCategoryName Parms{};

	Parms.InName = std::move(InName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnUpdateGradeColor
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             InGradeName                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class FName                             InColorTableKey                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ItemTooltip_Equip_Frame_C::OnUpdateGradeColor(const class FText& InGradeName, class FName InColorTableKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnUpdateGradeColor");

	Params::BP_ItemTooltip_Equip_Frame_C_OnUpdateGradeColor Parms{};

	Parms.InGradeName = std::move(InGradeName);
	Parms.InColorTableKey = InColorTableKey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnUpdateItemName
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             InName                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBP_ItemTooltip_Equip_Frame_C::OnUpdateItemName(const class FText& InName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnUpdateItemName");

	Params::BP_ItemTooltip_Equip_Frame_C_OnUpdateItemName Parms{};

	Parms.InName = std::move(InName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnPresetInfoUpdate
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    InIsOtherPreset                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_ItemTooltip_Equip_Frame_C::OnPresetInfoUpdate(const bool InIsOtherPreset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnPresetInfoUpdate");

	Params::BP_ItemTooltip_Equip_Frame_C_OnPresetInfoUpdate Parms{};

	Parms.InIsOtherPreset = InIsOtherPreset;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_Frame.BP_ItemTooltip_Equip_Frame_C.OnItemLockUpdate
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    InLock                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_ItemTooltip_Equip_Frame_C::OnItemLockUpdate(const bool InLock)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_Frame_C", "OnItemLockUpdate");

	Params::BP_ItemTooltip_Equip_Frame_C_OnItemLockUpdate Parms{};

	Parms.InLock = InLock;

	UObject::ProcessEvent(Func, &Parms);
}

}

