#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Interactable_Mark

#include "Basic.hpp"

#include "BP_Interactable_Mark_classes.hpp"
#include "BP_Interactable_Mark_parameters.hpp"


namespace SDK
{

// Function BP_Interactable_Mark.BP_Interactable_Mark_C.ExecuteUbergraph_BP_Interactable_Mark
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Interactable_Mark_C::ExecuteUbergraph_BP_Interactable_Mark(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Interactable_Mark_C", "ExecuteUbergraph_BP_Interactable_Mark");

	Params::BP_Interactable_Mark_C_ExecuteUbergraph_BP_Interactable_Mark Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Interactable_Mark.BP_Interactable_Mark_C.OnHideKeyIcon
// (Event, Protected, BlueprintEvent)

void UBP_Interactable_Mark_C::OnHideKeyIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Interactable_Mark_C", "OnHideKeyIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Interactable_Mark.BP_Interactable_Mark_C.OnShowKeyIcon
// (Event, Protected, BlueprintEvent)

void UBP_Interactable_Mark_C::OnShowKeyIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Interactable_Mark_C", "OnShowKeyIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Interactable_Mark.BP_Interactable_Mark_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_Interactable_Mark_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Interactable_Mark_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Interactable_Mark.BP_Interactable_Mark_C.OnShowEnableIcon
// (Event, Protected, BlueprintEvent)

void UBP_Interactable_Mark_C::OnShowEnableIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Interactable_Mark_C", "OnShowEnableIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Interactable_Mark.BP_Interactable_Mark_C.OnShowDisableIcon
// (Event, Protected, BlueprintEvent)

void UBP_Interactable_Mark_C::OnShowDisableIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Interactable_Mark_C", "OnShowDisableIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Interactable_Mark.BP_Interactable_Mark_C.OnHideMainActionIcon
// (Event, Protected, BlueprintEvent)

void UBP_Interactable_Mark_C::OnHideMainActionIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Interactable_Mark_C", "OnHideMainActionIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Interactable_Mark.BP_Interactable_Mark_C.OnShowMainActionIcon
// (Event, Protected, BlueprintEvent)

void UBP_Interactable_Mark_C::OnShowMainActionIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Interactable_Mark_C", "OnShowMainActionIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Interactable_Mark.BP_Interactable_Mark_C.OnCastingStart
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bInMyPcCasting                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bInCooperative                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bInShowCooperateNum                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_Interactable_Mark_C::OnCastingStart(const bool bInMyPcCasting, const bool bInCooperative, const bool bInShowCooperateNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Interactable_Mark_C", "OnCastingStart");

	Params::BP_Interactable_Mark_C_OnCastingStart Parms{};

	Parms.bInMyPcCasting = bInMyPcCasting;
	Parms.bInCooperative = bInCooperative;
	Parms.bInShowCooperateNum = bInShowCooperateNum;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Interactable_Mark.BP_Interactable_Mark_C.OnCastingEnd
// (Event, Protected, BlueprintEvent)
// Parameters:
// ECastingEndReason                       CastingEndReason                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bInMyPcCasting                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bInShowCooperateNum                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_Interactable_Mark_C::OnCastingEnd(ECastingEndReason CastingEndReason, const bool bInMyPcCasting, const bool bInShowCooperateNum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Interactable_Mark_C", "OnCastingEnd");

	Params::BP_Interactable_Mark_C_OnCastingEnd Parms{};

	Parms.CastingEndReason = CastingEndReason;
	Parms.bInMyPcCasting = bInMyPcCasting;
	Parms.bInShowCooperateNum = bInShowCooperateNum;

	UObject::ProcessEvent(Func, &Parms);
}

}

