#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ItemToolTip_ContextMenu_ConsoleBTN

#include "Basic.hpp"

#include "BP_ItemToolTip_ContextMenu_ConsoleBTN_classes.hpp"
#include "BP_ItemToolTip_ContextMenu_ConsoleBTN_parameters.hpp"


namespace SDK
{

// Function BP_ItemToolTip_ContextMenu_ConsoleBTN.BP_ItemToolTip_ContextMenu_ConsoleBTN_C.ExecuteUbergraph_BP_ItemToolTip_ContextMenu_ConsoleBTN
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ItemToolTip_ContextMenu_ConsoleBTN_C::ExecuteUbergraph_BP_ItemToolTip_ContextMenu_ConsoleBTN(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemToolTip_ContextMenu_ConsoleBTN_C", "ExecuteUbergraph_BP_ItemToolTip_ContextMenu_ConsoleBTN");

	Params::BP_ItemToolTip_ContextMenu_ConsoleBTN_C_ExecuteUbergraph_BP_ItemToolTip_ContextMenu_ConsoleBTN Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemToolTip_ContextMenu_ConsoleBTN.BP_ItemToolTip_ContextMenu_ConsoleBTN_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_ItemToolTip_ContextMenu_ConsoleBTN_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemToolTip_ContextMenu_ConsoleBTN_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

