#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ItemTooltip_Equip_StatType_6

#include "Basic.hpp"

#include "BP_ItemTooltip_Equip_StatType_6_classes.hpp"
#include "BP_ItemTooltip_Equip_StatType_6_parameters.hpp"


namespace SDK
{

// Function BP_ItemTooltip_Equip_StatType_6.BP_ItemTooltip_Equip_StatType_6_C.ExecuteUbergraph_BP_ItemTooltip_Equip_StatType_6
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ItemTooltip_Equip_StatType_6_C::ExecuteUbergraph_BP_ItemTooltip_Equip_StatType_6(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_StatType_6_C", "ExecuteUbergraph_BP_ItemTooltip_Equip_StatType_6");

	Params::BP_ItemTooltip_Equip_StatType_6_C_ExecuteUbergraph_BP_ItemTooltip_Equip_StatType_6 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemTooltip_Equip_StatType_6.BP_ItemTooltip_Equip_StatType_6_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_ItemTooltip_Equip_StatType_6_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemTooltip_Equip_StatType_6_C", "PreConstruct");

	Params::BP_ItemTooltip_Equip_StatType_6_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

