#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MarkupWidget_Tooltip

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_MarkupWidget_Tooltip.BP_MarkupWidget_Tooltip_C.ExecuteUbergraph_BP_MarkupWidget_Tooltip
// 0x0004 (0x0004 - 0x0000)
struct BP_MarkupWidget_Tooltip_C_ExecuteUbergraph_BP_MarkupWidget_Tooltip final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MarkupWidget_Tooltip_C_ExecuteUbergraph_BP_MarkupWidget_Tooltip) == 0x000004, "Wrong alignment on BP_MarkupWidget_Tooltip_C_ExecuteUbergraph_BP_MarkupWidget_Tooltip");
static_assert(sizeof(BP_MarkupWidget_Tooltip_C_ExecuteUbergraph_BP_MarkupWidget_Tooltip) == 0x000004, "Wrong size on BP_MarkupWidget_Tooltip_C_ExecuteUbergraph_BP_MarkupWidget_Tooltip");
static_assert(offsetof(BP_MarkupWidget_Tooltip_C_ExecuteUbergraph_BP_MarkupWidget_Tooltip, EntryPoint) == 0x000000, "Member 'BP_MarkupWidget_Tooltip_C_ExecuteUbergraph_BP_MarkupWidget_Tooltip::EntryPoint' has a wrong offset!");

}

