#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MagicDoll_Tooltip_Effect

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "TLClient_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_MagicDoll_Tooltip_Effect.BP_MagicDoll_Tooltip_Effect_C
// 0x0010 (0x1440 - 0x1430)
class UBP_MagicDoll_Tooltip_Effect_C final : public UTLUserWidgetFrame
{
public:
	uint8                                         Pad_1428[0x8];                                     // 0x1428(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1430(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBP_MagicDoll_SubStat_C*                BP_MagicDoll_Detail_SkillStat_Text;                // 0x1438(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_MagicDoll_Tooltip_Effect(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MagicDoll_Tooltip_Effect_C">();
	}
	static class UBP_MagicDoll_Tooltip_Effect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MagicDoll_Tooltip_Effect_C>();
	}
};
static_assert(alignof(UBP_MagicDoll_Tooltip_Effect_C) == 0x000010, "Wrong alignment on UBP_MagicDoll_Tooltip_Effect_C");
static_assert(sizeof(UBP_MagicDoll_Tooltip_Effect_C) == 0x001440, "Wrong size on UBP_MagicDoll_Tooltip_Effect_C");
static_assert(offsetof(UBP_MagicDoll_Tooltip_Effect_C, UberGraphFrame) == 0x001430, "Member 'UBP_MagicDoll_Tooltip_Effect_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_MagicDoll_Tooltip_Effect_C, BP_MagicDoll_Detail_SkillStat_Text) == 0x001438, "Member 'UBP_MagicDoll_Tooltip_Effect_C::BP_MagicDoll_Detail_SkillStat_Text' has a wrong offset!");

}

