#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MainMenu_AudioBTN_0

#include "Basic.hpp"

#include "BP_MainMenu_AudioBTN_0_classes.hpp"
#include "BP_MainMenu_AudioBTN_0_parameters.hpp"


namespace SDK
{

// Function BP_MainMenu_AudioBTN.BP_MainMenu_AudioBTN_C.ExecuteUbergraph_BP_MainMenu_AudioBTN
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void BP_MainMenu_AudioBTN_0::UBP_MainMenu_AudioBTN_C::ExecuteUbergraph_BP_MainMenu_AudioBTN(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MainMenu_AudioBTN_C", "ExecuteUbergraph_BP_MainMenu_AudioBTN");

	Params::BP_MainMenu_AudioBTN_C_ExecuteUbergraph_BP_MainMenu_AudioBTN Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MainMenu_AudioBTN.BP_MainMenu_AudioBTN_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void BP_MainMenu_AudioBTN_0::UBP_MainMenu_AudioBTN_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MainMenu_AudioBTN_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

