#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PolyMorph_Tooltip_Portrait

#include "Basic.hpp"

#include "BP_PolyMorph_Tooltip_Portrait_classes.hpp"
#include "BP_PolyMorph_Tooltip_Portrait_parameters.hpp"


namespace SDK
{

// Function BP_PolyMorph_Tooltip_Portrait.BP_PolyMorph_Tooltip_Portrait_C.ExecuteUbergraph_BP_PolyMorph_Tooltip_Portrait
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PolyMorph_Tooltip_Portrait_C::ExecuteUbergraph_BP_PolyMorph_Tooltip_Portrait(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PolyMorph_Tooltip_Portrait_C", "ExecuteUbergraph_BP_PolyMorph_Tooltip_Portrait");

	Params::BP_PolyMorph_Tooltip_Portrait_C_ExecuteUbergraph_BP_PolyMorph_Tooltip_Portrait Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PolyMorph_Tooltip_Portrait.BP_PolyMorph_Tooltip_Portrait_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_PolyMorph_Tooltip_Portrait_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PolyMorph_Tooltip_Portrait_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

