#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Target_NameCard_WeaponIcon

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Target_NameCard_WeaponIcon.BP_Target_NameCard_WeaponIcon_C.ExecuteUbergraph_BP_Target_NameCard_WeaponIcon
// 0x0004 (0x0004 - 0x0000)
struct BP_Target_NameCard_WeaponIcon_C_ExecuteUbergraph_BP_Target_NameCard_WeaponIcon final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Target_NameCard_WeaponIcon_C_ExecuteUbergraph_BP_Target_NameCard_WeaponIcon) == 0x000004, "Wrong alignment on BP_Target_NameCard_WeaponIcon_C_ExecuteUbergraph_BP_Target_NameCard_WeaponIcon");
static_assert(sizeof(BP_Target_NameCard_WeaponIcon_C_ExecuteUbergraph_BP_Target_NameCard_WeaponIcon) == 0x000004, "Wrong size on BP_Target_NameCard_WeaponIcon_C_ExecuteUbergraph_BP_Target_NameCard_WeaponIcon");
static_assert(offsetof(BP_Target_NameCard_WeaponIcon_C_ExecuteUbergraph_BP_Target_NameCard_WeaponIcon, EntryPoint) == 0x000000, "Member 'BP_Target_NameCard_WeaponIcon_C_ExecuteUbergraph_BP_Target_NameCard_WeaponIcon::EntryPoint' has a wrong offset!");

}

