#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TLInGameMode

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_TLInGameMode.BP_TLInGameMode_C.ExecuteUbergraph_BP_TLInGameMode
// 0x0004 (0x0004 - 0x0000)
struct BP_TLInGameMode_C_ExecuteUbergraph_BP_TLInGameMode final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_TLInGameMode_C_ExecuteUbergraph_BP_TLInGameMode) == 0x000004, "Wrong alignment on BP_TLInGameMode_C_ExecuteUbergraph_BP_TLInGameMode");
static_assert(sizeof(BP_TLInGameMode_C_ExecuteUbergraph_BP_TLInGameMode) == 0x000004, "Wrong size on BP_TLInGameMode_C_ExecuteUbergraph_BP_TLInGameMode");
static_assert(offsetof(BP_TLInGameMode_C_ExecuteUbergraph_BP_TLInGameMode, EntryPoint) == 0x000000, "Member 'BP_TLInGameMode_C_ExecuteUbergraph_BP_TLInGameMode::EntryPoint' has a wrong offset!");

}

