#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Tooltip_Codex_ACH_List

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Tooltip_Codex_ACH_List.BP_Tooltip_Codex_ACH_List_C.ExecuteUbergraph_BP_Tooltip_Codex_ACH_List
// 0x0004 (0x0004 - 0x0000)
struct BP_Tooltip_Codex_ACH_List_C_ExecuteUbergraph_BP_Tooltip_Codex_ACH_List final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Tooltip_Codex_ACH_List_C_ExecuteUbergraph_BP_Tooltip_Codex_ACH_List) == 0x000004, "Wrong alignment on BP_Tooltip_Codex_ACH_List_C_ExecuteUbergraph_BP_Tooltip_Codex_ACH_List");
static_assert(sizeof(BP_Tooltip_Codex_ACH_List_C_ExecuteUbergraph_BP_Tooltip_Codex_ACH_List) == 0x000004, "Wrong size on BP_Tooltip_Codex_ACH_List_C_ExecuteUbergraph_BP_Tooltip_Codex_ACH_List");
static_assert(offsetof(BP_Tooltip_Codex_ACH_List_C_ExecuteUbergraph_BP_Tooltip_Codex_ACH_List, EntryPoint) == 0x000000, "Member 'BP_Tooltip_Codex_ACH_List_C_ExecuteUbergraph_BP_Tooltip_Codex_ACH_List::EntryPoint' has a wrong offset!");

}

