#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TLGameInstance

#include "Basic.hpp"

#include "TLClient_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TLGameInstance.BP_TLGameInstance_C
// 0x0000 (0x04A0 - 0x04A0)
class UBP_TLGameInstance_C final : public UTLGameInstance
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_TLGameInstance_C">();
	}
	static class UBP_TLGameInstance_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_TLGameInstance_C>();
	}
};
static_assert(alignof(UBP_TLGameInstance_C) == 0x000010, "Wrong alignment on UBP_TLGameInstance_C");
static_assert(sizeof(UBP_TLGameInstance_C) == 0x0004A0, "Wrong size on UBP_TLGameInstance_C");

}

