#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UI_BTN_TextType

#include "Basic.hpp"

#include "BP_UI_BTN_TextType_classes.hpp"
#include "BP_UI_BTN_TextType_parameters.hpp"


namespace SDK
{

// Function BP_UI_BTN_TextType.BP_UI_BTN_TextType_C.ExecuteUbergraph_BP_UI_BTN_TextType
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_UI_BTN_TextType_C::ExecuteUbergraph_BP_UI_BTN_TextType(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UI_BTN_TextType_C", "ExecuteUbergraph_BP_UI_BTN_TextType");

	Params::BP_UI_BTN_TextType_C_ExecuteUbergraph_BP_UI_BTN_TextType Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UI_BTN_TextType.BP_UI_BTN_TextType_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_UI_BTN_TextType_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UI_BTN_TextType_C", "PreConstruct");

	Params::BP_UI_BTN_TextType_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UI_BTN_TextType.BP_UI_BTN_TextType_C.GreenHoverColorSet
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_UI_BTN_TextType_C::GreenHoverColorSet()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UI_BTN_TextType_C", "GreenHoverColorSet");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UI_BTN_TextType.BP_UI_BTN_TextType_C.RedHoverColorSet
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_UI_BTN_TextType_C::RedHoverColorSet()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UI_BTN_TextType_C", "RedHoverColorSet");

	UObject::ProcessEvent(Func, nullptr);
}

}

