#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UI_BTN_PopUp_Close

#include "Basic.hpp"

#include "BP_UI_BTN_PopUp_Close_classes.hpp"
#include "BP_UI_BTN_PopUp_Close_parameters.hpp"


namespace SDK
{

// Function BP_UI_BTN_PopUp_Close.BP_UI_BTN_PopUp_Close_C.ExecuteUbergraph_BP_UI_BTN_PopUp_Close
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_UI_BTN_PopUp_Close_C::ExecuteUbergraph_BP_UI_BTN_PopUp_Close(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UI_BTN_PopUp_Close_C", "ExecuteUbergraph_BP_UI_BTN_PopUp_Close");

	Params::BP_UI_BTN_PopUp_Close_C_ExecuteUbergraph_BP_UI_BTN_PopUp_Close Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UI_BTN_PopUp_Close.BP_UI_BTN_PopUp_Close_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_UI_BTN_PopUp_Close_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UI_BTN_PopUp_Close_C", "PreConstruct");

	Params::BP_UI_BTN_PopUp_Close_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

