#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UI_Slot_Texture

#include "Basic.hpp"

#include "BP_UI_Slot_Texture_classes.hpp"
#include "BP_UI_Slot_Texture_parameters.hpp"


namespace SDK
{

// Function BP_UI_Slot_Texture.BP_UI_Slot_Texture_C.ExecuteUbergraph_BP_UI_Slot_Texture
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_UI_Slot_Texture_C::ExecuteUbergraph_BP_UI_Slot_Texture(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UI_Slot_Texture_C", "ExecuteUbergraph_BP_UI_Slot_Texture");

	Params::BP_UI_Slot_Texture_C_ExecuteUbergraph_BP_UI_Slot_Texture Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UI_Slot_Texture.BP_UI_Slot_Texture_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_UI_Slot_Texture_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UI_Slot_Texture_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UI_Slot_Texture.BP_UI_Slot_Texture_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_UI_Slot_Texture_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UI_Slot_Texture_C", "PreConstruct");

	Params::BP_UI_Slot_Texture_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UI_Slot_Texture.BP_UI_Slot_Texture_C.UnCheck_Hover_State
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_UI_Slot_Texture_C::UnCheck_Hover_State()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UI_Slot_Texture_C", "UnCheck_Hover_State");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UI_Slot_Texture.BP_UI_Slot_Texture_C.UnCheck_Normal_State
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_UI_Slot_Texture_C::UnCheck_Normal_State()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UI_Slot_Texture_C", "UnCheck_Normal_State");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UI_Slot_Texture.BP_UI_Slot_Texture_C.Check_Normal_State
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_UI_Slot_Texture_C::Check_Normal_State()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UI_Slot_Texture_C", "Check_Normal_State");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UI_Slot_Texture.BP_UI_Slot_Texture_C.Check_Hover_State
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_UI_Slot_Texture_C::Check_Hover_State()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UI_Slot_Texture_C", "Check_Hover_State");

	UObject::ProcessEvent(Func, nullptr);
}

}

