#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CollectionContextMenu

#include "Basic.hpp"

#include "CollectionContextMenu_classes.hpp"
#include "CollectionContextMenu_parameters.hpp"


namespace SDK
{

// Function CollectionContextMenu.CollectionContextMenu_C.ExecuteUbergraph_CollectionContextMenu
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCollectionContextMenu_C::ExecuteUbergraph_CollectionContextMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CollectionContextMenu_C", "ExecuteUbergraph_CollectionContextMenu");

	Params::CollectionContextMenu_C_ExecuteUbergraph_CollectionContextMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CollectionContextMenu.CollectionContextMenu_C.OnContextMenuShow
// (Event, Public, BlueprintEvent)
// Parameters:
// EInvenModeType                          InInvenModeType                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTLUserWidgetItemSlot*            InItemWidget                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   InCurrentPresetNum                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ETLUIPlatform                           UIPlatform                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCollectionContextMenu_C::OnContextMenuShow(EInvenModeType InInvenModeType, class UTLUserWidgetItemSlot* InItemWidget, int32 InCurrentPresetNum, ETLUIPlatform UIPlatform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CollectionContextMenu_C", "OnContextMenuShow");

	Params::CollectionContextMenu_C_OnContextMenuShow Parms{};

	Parms.InInvenModeType = InInvenModeType;
	Parms.InItemWidget = InItemWidget;
	Parms.InCurrentPresetNum = InCurrentPresetNum;
	Parms.UIPlatform = UIPlatform;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CollectionContextMenu.CollectionContextMenu_C.Add Enchant Menu
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTLUserWidgetItemSlot*            InItemWidget                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCollectionContextMenu_C::Add_Enchant_Menu(class UTLUserWidgetItemSlot* InItemWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CollectionContextMenu_C", "Add Enchant Menu");

	Params::CollectionContextMenu_C_Add_Enchant_Menu Parms{};

	Parms.InItemWidget = InItemWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CollectionContextMenu.CollectionContextMenu_C.AddTradeMenu
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTLUserWidgetItemSlot*            InItemWidget                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCollectionContextMenu_C::AddTradeMenu(class UTLUserWidgetItemSlot* InItemWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CollectionContextMenu_C", "AddTradeMenu");

	Params::CollectionContextMenu_C_AddTradeMenu Parms{};

	Parms.InItemWidget = InItemWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CollectionContextMenu.CollectionContextMenu_C.AddAcquisitionMenu
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTLUserWidgetItemSlot*            InItemWidget                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCollectionContextMenu_C::AddAcquisitionMenu(class UTLUserWidgetItemSlot* InItemWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CollectionContextMenu_C", "AddAcquisitionMenu");

	Params::CollectionContextMenu_C_AddAcquisitionMenu Parms{};

	Parms.InItemWidget = InItemWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CollectionContextMenu.CollectionContextMenu_C.AddCollectionMenu
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTLUserWidgetItemSlot*            InItemWidget                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCollectionContextMenu_C::AddCollectionMenu(class UTLUserWidgetItemSlot* InItemWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CollectionContextMenu_C", "AddCollectionMenu");

	Params::CollectionContextMenu_C_AddCollectionMenu Parms{};

	Parms.InItemWidget = InItemWidget;

	UObject::ProcessEvent(Func, &Parms);
}

}

