#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EventScene_Enchant_Lobby

#include "Basic.hpp"

#include "TLClient_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EventScene_Enchant_Lobby.EventScene_Enchant_Lobby_C
// 0x0000 (0x00C0 - 0x00C0)
class UEventScene_Enchant_Lobby_C final : public UTLEventScene
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EventScene_Enchant_Lobby_C">();
	}
	static class UEventScene_Enchant_Lobby_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEventScene_Enchant_Lobby_C>();
	}
};
static_assert(alignof(UEventScene_Enchant_Lobby_C) == 0x000010, "Wrong alignment on UEventScene_Enchant_Lobby_C");
static_assert(sizeof(UEventScene_Enchant_Lobby_C) == 0x0000C0, "Wrong size on UEventScene_Enchant_Lobby_C");

}

