#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GameLobbyActor_BP

#include "Basic.hpp"

#include "GameLobbyActor_BP_classes.hpp"
#include "GameLobbyActor_BP_parameters.hpp"


namespace SDK
{

// Function GameLobbyActor_BP.GameLobbyActor_BP_C.ExecuteUbergraph_GameLobbyActor_BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AGameLobbyActor_BP_C::ExecuteUbergraph_GameLobbyActor_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GameLobbyActor_BP_C", "ExecuteUbergraph_GameLobbyActor_BP");

	Params::GameLobbyActor_BP_C_ExecuteUbergraph_GameLobbyActor_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GameLobbyActor_BP.GameLobbyActor_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AGameLobbyActor_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GameLobbyActor_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

