#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NcAssetReferencer

#include "Basic.hpp"

#include "NcPlatformSdk_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NcAssetReferencer.NcAssetReferencer_C
// 0x0000 (0x0078 - 0x0078)
class UNcAssetReferencer_C final : public UNcAssetReferencer
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NcAssetReferencer_C">();
	}
	static class UNcAssetReferencer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNcAssetReferencer_C>();
	}
};
static_assert(alignof(UNcAssetReferencer_C) == 0x000008, "Wrong alignment on UNcAssetReferencer_C");
static_assert(sizeof(UNcAssetReferencer_C) == 0x000078, "Wrong size on UNcAssetReferencer_C");

}

