#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TLBase

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class TLBase.TLObject
// 0x0010 (0x0038 - 0x0028)
class UTLObject : public UObject
{
public:
	uint8                                         Pad_28[0x10];                                      // 0x0028(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"TLObject">();
	}
	static class UTLObject* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTLObject>();
	}
};
static_assert(alignof(UTLObject) == 0x000008, "Wrong alignment on UTLObject");
static_assert(sizeof(UTLObject) == 0x000038, "Wrong size on UTLObject");

}

