#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tutorial_Master04

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "TLClient_classes.hpp"
#include "TLScheme_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Tutorial_Master04.Tutorial_Master04_C
// 0x0010 (0x06D0 - 0x06C0)
class UTutorial_Master04_C final : public UTLTutorialConditionObject
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x06C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         Cooldown;                                          // 0x06C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Tutorial_Master04(int32 EntryPoint);
	void ___t___0(const EWeaponCategory WeaponCategory, const int32 UIPriority);
	void OnEventPartyActivate_Event_0(bool InActivate);
	void OnCreate();
	void OnEventCompleteTutorial_Event_0(class FName TutorialTableId, bool bSkip);
	void TLMap_pt0___(class FName CheckRowName, class FName* CheckName, int32* CheckUID);
	void TLEventEffect_pt0___(class FName CheckRowName, class FName* CheckName);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Tutorial_Master04_C">();
	}
	static class UTutorial_Master04_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTutorial_Master04_C>();
	}
};
static_assert(alignof(UTutorial_Master04_C) == 0x000008, "Wrong alignment on UTutorial_Master04_C");
static_assert(sizeof(UTutorial_Master04_C) == 0x0006D0, "Wrong size on UTutorial_Master04_C");
static_assert(offsetof(UTutorial_Master04_C, UberGraphFrame) == 0x0006C0, "Member 'UTutorial_Master04_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UTutorial_Master04_C, Cooldown) == 0x0006C8, "Member 'UTutorial_Master04_C::Cooldown' has a wrong offset!");

}

