#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Volume_Talland

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Volume_Talland.Volume_Talland_C
// 0x0000 (0x0238 - 0x0238)
class AVolume_Talland_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Volume_Talland_C">();
	}
	static class AVolume_Talland_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AVolume_Talland_C>();
	}
};
static_assert(alignof(AVolume_Talland_C) == 0x000008, "Wrong alignment on AVolume_Talland_C");
static_assert(sizeof(AVolume_Talland_C) == 0x000238, "Wrong size on AVolume_Talland_C");

}

