#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Volume_Tutorial_TalkingIsland

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Volume_Tutorial_TalkingIsland.Volume_Tutorial_TalkingIsland_C
// 0x0000 (0x0238 - 0x0238)
class AVolume_Tutorial_TalkingIsland_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Volume_Tutorial_TalkingIsland_C">();
	}
	static class AVolume_Tutorial_TalkingIsland_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AVolume_Tutorial_TalkingIsland_C>();
	}
};
static_assert(alignof(AVolume_Tutorial_TalkingIsland_C) == 0x000008, "Wrong alignment on AVolume_Tutorial_TalkingIsland_C");
static_assert(sizeof(AVolume_Tutorial_TalkingIsland_C) == 0x000238, "Wrong size on AVolume_Tutorial_TalkingIsland_C");

}

